telegram:
  token: "8629251193:AAErpWdzt_vNpkfhlxN8aiXlLgWkfM7h5QQ"
  username: "TGBotPluginBot"
admins:
  - 7742036100
  - 6343309173
registration:
  timeout-seconds: 20
  reminder-interval-seconds: 3
